

//  Shourav Rakshit Ivan, Alisha Lalani, Saadman Rahman, ------------, Manvi Juneja,
//  Zaid Nissar, Qusai Dahodwalla, Shree Patel, Vidhi Soni

import Firebase
import FirebaseFirestore

// MARK: - Post Struct
// This structure represents a post in the application. It contains various properties
// to store information about the post, such as description, location, image URLs, user data, etc.
struct Post: Identifiable {
    let id: String                    // Unique identifier for the post (typically generated by Firestore).
    let description: String           // A textual description or content of the post.
    let rating: Int                   // Rating of the post (e.g., 1-5 stars).
    let locationRef: DocumentReference // Reference to the location document in Firestore.
    let locationAddress: String       // Physical address of the location associated with the post.
    let imageUrls: [String]           // An array of URLs for images associated with the post.
    let timestamp: Date               // Timestamp when the post was created.
    let uid: String                   // User ID of the person who created the post (from Firebase Authentication).
    let username: String              // Username of the person who created the post.
    let userProfileImageUrl: String   // URL to the user's profile image.
    
    // MARK: - Mutable properties for post interaction
    var commentCount: Int = 0         // Default value is 0. It can be updated later when comments are added.
    var likesCount: Int = 0           // Default value is 0. It can be updated later when the post is liked or unliked.
    var likedByUserIds: [String] = [] // Default to an empty array. It holds the user IDs of users who have liked the post.
    var liked: Bool = false           // Initialized to `false`. Represents whether the current user has liked the post or not.
}

